name: deploy on push production branch
on:
  push:
    branches:
      - prod

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: build the code
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: prepare server environment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html
            if ! command -v nginx > /dev/null; then
              sudo apt-get update && sudo apt-get install -y nginx
            fi
            sudo chown -R ubuntu:ubuntu /var/www/html

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./dist/*"
          target: "/var/www/html"
          strip_components: 1

      - name: set the root user back as the owner
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R root:root /var/www/html
            sudo systemctl restart nginx